# Utiliser l'image de base Nginx
FROM nginx:latest

# Copier les fichiers de configuration et les fichiers front-end
COPY ./softy-pinko-front-end /usr/share/nginx/html
COPY ./softy-pinko-front-end.conf /etc/nginx/conf.d/default.conf
