version: '3'

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: task4-front-end:latest
    ports:
      - "80:80"

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: task4-back-end:latest
    ports:
      - "5252:5252"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task4
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
