version: '3'
services:
  front-end:
    image: softy-pinko-front-end:task3  # Assurez-vous que c'est la bonne version
    ports:
      - "80:80"  # Expose port 80 pour le front-end

  back-end:
    image: task4-back-end  # Utilisez l'image correcte pour le task4
    ports:
      - "5252:5252"  # Expose port 5252 pour le back-end

  proxy:
    image: softy-pinko-proxy:task4  # Assurez-vous d'utiliser la bonne image pour le task4
    ports:
      - "80:80"  # Expose port 80 pour le proxy
    depends_on:
      - front-end
      - back-end
