services:
  front-end:
    image: softy-pinko-front-end:task4
    ports:
      - "80:80"

  back-end:
    image: softy-pinko-back-end:task4
    ports:
      - "5252:5252"

  proxy:
    image: softy-pinko-proxy:task4
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
