version: '3'
services:
  front-end:
    image: task4-front-end:latest
    ports:
      - "80:80"  # Mappe le port 80 du conteneur au port 80 de l'hôte

  back-end:
    image: task4-back-end:latest
    ports:
      - "5252:5252"  # Mappe le port 5252 du conteneur au port 5252 de l'hôte

  proxy:
    image: softy-pinko-proxy:task4  # Assurez-vous que cette image est construite
    ports:
      - "80:80"  # Mappe le port 80 du conteneur au port 80 de l'hôte
    depends_on:
      - front-end
      - back-end
