version: '3'
services:
  front-end:
    image: softy-pinko-front-end:task4
    ports:
      - "80:80"  # Expose port 80 for front-end

  back-end:
    image: softy-pinko-back-end:task4
    ports:
      - "5252:5252"  # Expose port 5252 for back-end

  proxy:
    image: softy-pinko-proxy:task4
    ports:
      - "80:80"  # Expose port 80 for proxy
    depends_on:
      - front-end
      - back-end
