services:
  front-end:
    image: softy-pinko-front-end:task4
    # Retiré l'exposition directe du port pour le front-end
    # ports:
    #   - "80:80"

  back-end:
    image: softy-pinko-back-end:task4
    # Retiré l'exposition directe du port pour le back-end
    # ports:
    #   - "5252:5252"

  proxy:
    image: softy-pinko-proxy:task4
    ports:
      - "80:80"  # Expose port 80 pour le proxy
    depends_on:
      - front-end
      - back-end
    # Optionnel : Ajoutez un volume si vous avez besoin de monter un fichier de configuration
    # volumes:
    #   - ./proxy.conf:/etc/nginx/conf.d/default.conf
