# Utiliser l'image Ubuntu la plus récente comme base
FROM ubuntu:latest

# Mettre à jour la liste des paquets
RUN apt-get update

# Mettre à jour les logiciels installés
RUN apt-get upgrade -y

# Définir la commande par défaut pour le conteneur
CMD echo "Hello, World!"
