services:
  front-end:
    image: softy-pinko-front-end:task5
    ports:
      - "80:80"

  back-end:
    image: softy-pinko-back-end:task5
    ports:
      - "5252:5252"

  proxy:
    image: softy-pinko-proxy:task5
    ports:
      - "80:80"  # Expose port 80 for proxy
    depends_on:
      - front-end
      - back-end
    # Optionnel : Ajoutez un volume si vous avez besoin de monter un fichier de configuration
    # volumes:
    #   - ./proxy.conf:/etc/nginx/conf.d/default.conf
