services:
  front-end:
    image: softy-pinko-front-end:task5
    build:
      context: ./task5/front-end
      dockerfile: Dockerfile
    ports:
      - "80:80"

  back-end:
    image: softy-pinko-back-end:task5
    build:
      context: ./task5/back-end
      dockerfile: Dockerfile
    ports:
      - "5252:5252"

  proxy:
    image: softy-pinko-proxy:task5
    build:
      context: ./task5/proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
