version: '3'
services:
  front-end:
    image: softy-pinko-front-end:task5
    ports:
      - "80:80"  # Expose port 80 pour le front-end

  back-end:
    image: softy-pinko-back-end:task5
    ports:
      - "5252:5252"  # Expose port 5252 pour le back-end

  proxy:
    image: softy-pinko-proxy:task5
    ports:
      - "80:80"  # Expose port 80 pour le proxy
    depends_on:
      - front-end
      - back-end
    # Optionnel : Ajoutez un volume si vous avez besoin de monter un fichier de configuration
    # volumes:
    #   - ./proxy.conf:/etc/nginx/conf.d/default.conf
